language: node_js
node_js:
  - '9'
before_install:
  - npm install -g nyc
  - npm install -g mocha
install:
  - npm install
  - npm run fetch_libdefs
  - npm run build

script:
  - npm run test_with_report

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
